name: Build and deploy to ECR

on:

  push:
    branches: [ master ]
  
jobs:

  build:

    name: build_and_push
    runs-on: ubuntu-latest


    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      run: |
        pip install poetry
        make init


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


    # - name: Push image to ECR
    #   env:
    #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #     ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
    #     IMAGE_TAG: 